config/routes.rb
Rails.application.routes.draw do

 
  get 'news/index'

  root 'welcomes#index'
  resources :welcomes
  get '/trends' => 'welcomes#trend'
  get '/faqs' => 'welcomes#faq'
  get '/terms_of_serives' => 'welcomes#terms_of_serives'
  get '/privacy_policys' => 'welcomes#privacy_policy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,  :controllers => {:registrations => "users/registrations"}

  resources :posts do
    resources :comments
  end  
  resources :jobs
  
  resources :conversations do 
  resources :messages 
  end
  
  resources :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
has_many :messages , dependent: :destroy

belongs_to :sender , :foreign_key =>  :sender_id, :class_name => "User"
belongs_to :rec , :foreign_key => :rec_id, :class_name => "User"

scope :between, ->(sender_id,rec_id) do 
    where("(conversations.sender_id = ? AND conversations.rec_id = ?) OR (conversations.sender_id = ? AND conversations.rec_id = ?)",sender_id,rec_id,rec_id,sender_id)
end
	
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation

  def message_time
    created_at.strftime("%m%d%y at %l:%M %p")
  end

  
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  has_many :posts
  has_many :comments
  has_many :messages
  has_many :conversations , :foreign_key => :sender_id , :class_name => "Conversation"
  has_many :conversations , :foreign_key => :rec_id , :class_name => "Conversation"

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		# @comment.update_attributes(user_id: current_user.id)
		 if @comment.save
		 	flash[:notice] = "Success"
		 else
		 	flash[:error] = @comment.errors.full_messages
		 end
		redirect_to post_path(@post)

	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
  			if @comment.update(comment_params)
  				flash[:notice] = "Success"
    			redirect_to @post
  			else
    			render 'edit'
  			end
	end

	def destroy
    	@post = Post.find(params[:post_id])
    	@comment = @post.comments.find(params[:id])
    	@comment.destroy
    	flash[:notice] = "Success"
    	redirect_to post_path(@post)
  	end
	private 
	def comment_params
		params.require(:comment).permit(:comment, :user_id, :post_id)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@jobs = Job.all
  end
  def new
  	@job = Job.new
  end

  def create
  	@job = Job.new(job_params)
  	if @job.save
  		redirect_to jobs_path
  	else
  		root_path
  	end
  end

  def show
  	@job = Job.find(params[:id])
  end

  private
  def job_params
  	params.require(:job).permit(:company_name,
   :job_title,
   :job_location,
   :salary,
   :experience,
   :sector,
   :skill,
   :level_of_experience,
   :corporate_type,
   :job_description)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action do 
       @conversation = Conversation.find(params[:conversation_id])
    end
		
	
	def index
		#@messages = @conversation.messages.all
      
		 @messages = @conversation.messages
			  if @messages.length > 10
			   @over_ten = true
			   @messages = @messages[-10..-1]
			  end
			  if params[:m]
			   @over_ten = false
			   @messages = @conversation.messages
			  end
			 if @messages.last
			  if @messages.last.user_id != current_user.id
			   @messages.last.read = true;
			  end
			 end
			@message = @conversation.messages.new
   end


	def new
	
       @message = @conversation.messages.new
	end

	def create
       @message = @conversation.messages.new(message_params)
       if @message.save
       	redirect_to conversation_messages_path(@conversation)
       end
	end

	private
	def message_params
		params.require(:message).permit(:subject,:message,:user_id)
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	before_action :authenticate_user!
  def index
  	@news = News.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
def index
		@posts = Post.all
	end
	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

 		# @post.update_attributes(user_id: current_user.id)
  		if @post.save
  			redirect_to @post
  		else
  			render 'new'
  		end
	end

	def update
  		@post = Post.find(params[:id])
 
  			if @post.update(post_params)
  			redirect_to @post
  			else
    		render 'edit'
  			end
	end

	def destroy
		@post = Post.find(params[:id])
  		@post.destroy
 		redirect_to posts_path
	end

	private
  	def post_params
    params.require(:post).permit(:title, :content)
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(params_user)
		if @user.save
			redirect_to root_path
		end
	end
private
def params_user
	params.require(:user).permit(:email, :password, :phone_no, :verification_code, :unique_id, :company_name, :hr_name, :hiring_agency,
	:sector,
    :skills,
    :level_of_experience,
    :experience,
    :corporate_type,
    :education_level,
    :major,
    :minor,
    :institution_type,
    :cerificate,
    :salary,
    :location,
    :city,
    :reloaction_status,
    :role)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.comment %>



  <%= link_to 'Edit Comment' , edit_post_comment_path(params[:id], comment)%>
||
  <%= link_to 'Destroy Comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>

</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p>
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<% @jobs.each do |j| %>
	company_name: <%= j.company_name %><br>
	job_title: <%= j.job_title %><br>
	job_location: <%= j.job_location %><br>
	salary:	<%= j.salary %><br>
	experience:	<%= j.experience %><br>
	sector:	<%= j.sector %><br>
	skill: <%= j.skill %><br>
	level_of_experience: <%= j.level_of_experience %><br>
	corporate_type:	<%= j.corporate_type %><br>
	job_description: <%= j.job_description %><br>
	===================================================================<br>
<% end %>

app/views/jobs/new.html.erb
<h1>Post a job </h1>

<%= form_for @job do |t|%>

      <div> <%=t.label :company_name%><br />
            <%=t.text_field :company_name%>
      </div>

      <div> <%=t.label :job_title%><br />
            <%=t.text_field :job_title%></div>

      <div> <%=t.label :job_location%><br />
            <%=t.select :job_location, [['India','India'],['Usa','Usa']], :include_blank => false%></div>

      <div> <%=t.label :salary%><br />
            $ <%=t.text_field :salary%>
            </div>

      <div> <%=t.label :experience%><br />
            <%=t.text_field :experience%></div>

      <div> <%=t.label :sector%><br />
            <%=t.text_field :sector%></div>

      <div> <%=t.label :skill%><br />
            <%=t.text_field :skill%></div>

      <div> <%=t.label :level_of_experience%><br />
            <%=t.select :level_of_experience, [['Master','Master'],['Expert','Expert'],['Proficient','Proficient'],['Learner','Learner'],['Beginer','Beginer']] %></div>

      <div> <%=t.label :corporate_type%><br />
            <%=t.select :corporate_type, [['Tier I','Tier I'],['Tier II','Tier II'],['Tier III','Tier III']]%></div>

      <div> <%=t.label :job_description%><br />
            <%=t.text_area :job_description%></div>

      <div class="actions">

      <%= t.submit "Post" %>
      </div>
<% end %>

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/messages/index.html.erb
<h1>My messages</h1>

<% if @over_ten %>
   <%= link_to 'Show Previous', '?m=all' %>
<% end %>




<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.subject %>
      <% user = User.find(message.user_id) %>
      <div class="item">
        <div class="content">
          <div class="header"><strong><%= user.email %></strong> <%= message.message_time %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon"></i>
              <%= message.subject %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>




<%= form_for [@conversation, @message], html: {class: "ui reply form"} do  |f|%>
  <div class="field">
    <%= f.text_area :subject, class: "form-control" %>
  </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
  <div>
    <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
  </div>

<% end %>

app/views/news/index.html.erb
<h1>News#index</h1>
<% @news.each do |f|%>
<h3><%= f.title %></h3>
<p><%= f.content %></p>
===============================================================
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<!--  
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  -->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/index.html.erb
<h1>Blog</h1>
<%= link_to 'New post', new_post_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td>
      <%=link_to post.title , post_path(post)%>
      </td>
      <td>
      <%= post.content %>
      </td>

    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2>Post</h2>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<%= link_to 'Edit', edit_post_path(@post)%>
--
<%= link_to 'Destroy',post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>


<h2>Comments</h2>
<%= render @post.comments %>

<h5>Added a comments:</h5>
<%= render 'comments/form' %>

<%= link_to 'Back', posts_path %>