config/routes.rb
Rails.application.routes.draw do

 
  get 'news/index'

  root 'welcomes#index'
  resources :welcomes
  get '/trends' => 'welcomes#trend'
  get '/faqs' => 'welcomes#faq'
  get '/terms_of_serives' => 'welcomes#terms_of_serives'
  get '/privacy_policys' => 'welcomes#privacy_policy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,  :controllers => {:registrations => "users/registrations"}

  resources :posts do
    resources :comments
  end  
  resources :jobs
  
  resources :conversations do 
  resources :messages 
  end
  
  resources :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
has_many :messages , dependent: :destroy

belongs_to :sender , :foreign_key =>  :sender_id, :class_name => "User"
belongs_to :rec , :foreign_key => :rec_id, :class_name => "User"

scope :between, ->(sender_id,rec_id) do 
    where("(conversations.sender_id = ? AND conversations.rec_id = ?) OR (conversations.sender_id = ? AND conversations.rec_id = ?)",sender_id,rec_id,rec_id,sender_id)
end
	
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation

  def message_time
    created_at.strftime("%m%d%y at %l:%M %p")
  end

  
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  has_many :posts
  has_many :comments
  has_many :messages
  has_many :conversations , :foreign_key => :sender_id , :class_name => "Conversation"
  has_many :conversations , :foreign_key => :rec_id , :class_name => "Conversation"

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		# @comment.update_attributes(user_id: current_user.id)
		 if @comment.save
		 	flash[:notice] = "Success"
		 else
		 	flash[:error] = @comment.errors.full_messages
		 end
		redirect_to post_path(@post)

	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
  			if @comment.update(comment_params)
  				flash[:notice] = "Success"
    			redirect_to @post
  			else
    			render 'edit'
  			end
	end

	def destroy
    	@post = Post.find(params[:post_id])
    	@comment = @post.comments.find(params[:id])
    	@comment.destroy
    	flash[:notice] = "Success"
    	redirect_to post_path(@post)
  	end
	private 
	def comment_params
		params.require(:comment).permit(:comment, :user_id, :post_id)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@jobs = Job.all
  end
  def new
  	@job = Job.new
  end

  def create
  	@job = Job.new(job_params)
  	if @job.save
  		redirect_to jobs_path
  	else
  		root_path
  	end
  end

  def show
  	@job = Job.find(params[:id])
  end

  private
  def job_params
  	params.require(:job).permit(:company_name,
   :job_title,
   :job_location,
   :salary,
   :experience,
   :sector,
   :skill,
   :level_of_experience,
   :corporate_type,
   :job_description)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action do 
       @conversation = Conversation.find(params[:conversation_id])
    end
		
	
	def index
		#@messages = @conversation.messages.all
      
		 @messages = @conversation.messages
			  if @messages.length > 10
			   @over_ten = true
			   @messages = @messages[-10..-1]
			  end
			  if params[:m]
			   @over_ten = false
			   @messages = @conversation.messages
			  end
			 if @messages.last
			  if @messages.last.user_id != current_user.id
			   @messages.last.read = true;
			  end
			 end
			@message = @conversation.messages.new
   end


	def new
	
       @message = @conversation.messages.new
	end

	def create
       @message = @conversation.messages.new(message_params)
       if @message.save
       	redirect_to conversation_messages_path(@conversation)
       end
	end

	private
	def message_params
		params.require(:message).permit(:subject,:message,:user_id)
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	before_action :authenticate_user!
  def index
  	@news = News.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
def index
		@posts = Post.all
	end
	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

 		# @post.update_attributes(user_id: current_user.id)
  		if @post.save
  			redirect_to @post
  		else
  			render 'new'
  		end
	end

	def update
  		@post = Post.find(params[:id])
 
  			if @post.update(post_params)
  			redirect_to @post
  			else
    		render 'edit'
  			end
	end

	def destroy
		@post = Post.find(params[:id])
  		@post.destroy
 		redirect_to posts_path
	end

	private
  	def post_params
    params.require(:post).permit(:title, :content)
  	end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end

	def create
		@user = User.new(params_user)
		logger.info "------#{@user.valid?} =======#{@user.errors.full_messages}"
		if @user.save
			redirect_to root_path
		end
	end
private
def params_user
	params.require(:user).permit(:email, :password, :phone_no, :verification_code, :unique_id, :company_name, :hr_name, :hiring_agency, :role)

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(params_user)
		if @user.save
			redirect_to root_path
		end
	end
private
def params_user
	params.require(:user).permit(:email, :password, :phone_no, :verification_code, :unique_id, :company_name, :hr_name, :hiring_agency,
	:sector,
    :skills,
    :level_of_experience,
    :experience,
    :corporate_type,
    :education_level,
    :major,
    :minor,
    :institution_type,
    :cerificate,
    :salary,
    :location,
    :city,
    :reloaction_status,
    :role)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/users/edit.html.erb
<% if params[:edit_as] == 'employer' %>



    <%= form_for @user do |f| %>
    <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>
      
      <div class="field">
        <%= f.label :company_name %><br />
        <%= f.text_field :company_name, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :hr_name %><br />
        <%= f.text_field :hr_name%>
      </div>
      <div class="field">
        <%= f.label :phone_no %><br />
        <%= f.text_field :phone_no, autocomplete: "off" %>
      </div>
      <div class="field">
        Hiring agency: <br />
        Yes<%= radio_button("user", "hiring_agency", true)%>
        No<%= radio_button("user", "hiring_agency", false) %>
      </div>
      <%= f.submit "Save Changes"%>
    <% end %>



<% else %>




    <%= form_for @user do |f| %>

    <div class="field">
            <%= f.label :sector %><br />
            <%= f.select :sector, [['Tecnology','Tecnology'],['finence','finence'],['Mangement','Mangement'],['bussiness','bussiness']] %>
      </div>

      <div class="field">
            <%= f.label :skills %><br />

      </div>

      <div class="field">
            <%= f.label :level_of_experience %><br />
            <%= f.select :level_of_experience, [['Master','Master'],['Expert','Expert'],['Proficient','Proficient'],['Learner','Learner'],['Beginer','Beginer']] %>
      </div>

      <div class="field">
            <%= f.label :experience %><br />
            <%= f.text_field :experience%>
      </div>

      <div class="field">
        <%= f.label :corporate_type %><br />
        <%= f.select :corporate_type, [['Tier I','Tier I'],['TierII','TierII'],['Tier III','Tier III']] %>
        </div>

          <div class="field">
            <%= f.label :education_level %><br />
            <%= f.select :education_level,  [['Associate','Associate'],['Bachelor','Bachelor'],['Master','Master'],['Master+','Master+']] %>
          </div>

          <div class="field">
            <%= f.label :major %><br />
            <%= f.text_field :major%>
          </div>

          <div class="field">
            <%= f.label :minor %><br />
            <%= f.text_field :minor%>
          </div>

          <div class="field">
            <%= f.label :institution_type %><br />
            <%= f.select :institution_type, [['Commerce','Commerce'],['Enginering','Enginering'],['Art','Art'],['Science','Science']] %>
          </div>

          <div class="field">
            <%= f.label :cerificate %><br />
            <%= f.text_field :cerificate%>
          </div>

          <div class="field">
            <%= f.label :salary %><br />
            <%= f.text_field :salary%>
          </div>

          <div class="field">
            <%= f.label :location %><br />
            <%= f.text_field :location %>
          </div>

          <div class="field">
            <%= f.label :city %><br />
            <%= f.text_field :city%>
          </div>

          <div class="field">
           Relocate?<br />
            Yes <%= radio_button("user", "reloaction_status", true)%>
            No <%= radio_button("user", "reloaction_status", false) %>
          </div>

          <%= f.submit "Update"%>

    <% end %>


<% end %> <!-- ending if -->

app/views/users/show.html.erb
<h1>User profile</h1>
<div align="center">
	<% if current_user.role == 'employer'%>
		<h2>Employer</h2>
		Email: <%= @user.email %><br>
		Company Name: <%= @user.company_name %><br>
		HR's name: <%= @user.hr_name %><br>
		Phone Number: <%= @user.phone_no %><br>
		Hiring Agency: <% if @user.hiring_agency == true %>Yes <% else %>No<% end %><br>
		<a href= "<%= current_user.id %>/edit?edit_as=employer"> Edit</a>
		
		<% else %>
		<h2>Professional</h2>
		<%= link_to "Edit", edit_user_path(current_user) %>
	<% end %>
</div>