config/routes.rb
Rails.application.routes.draw do

 
  get 'news/index'

  root 'welcomes#index'
  resources :welcomes
  get '/trends' => 'welcomes#trend'
  get '/faqs' => 'welcomes#faq'
  get '/terms_of_serives' => 'welcomes#terms_of_serives'
  get '/privacy_policys' => 'welcomes#privacy_policy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,  :controllers => {:registrations => "users/registrations"}

  resources :posts do
    resources :comments
  end  
  resources :jobs
  
  resources :conversations do 
  resources :messages 
  end
  
  resources :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
has_many :messages , dependent: :destroy

belongs_to :sender , :foreign_key =>  :sender_id, :class_name => "User"
belongs_to :rec , :foreign_key => :rec_id, :class_name => "User"

scope :between, ->(sender_id,rec_id) do 
    where("(conversations.sender_id = ? AND conversations.rec_id = ?) OR (conversations.sender_id = ? AND conversations.rec_id = ?)",sender_id,rec_id,rec_id,sender_id)
end
	
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation

  def message_time
    created_at.strftime("%m%d%y at %l:%M %p")
  end

  
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  has_many :posts
  has_many :comments
  has_many :messages
  has_many :conversations , :foreign_key => :sender_id , :class_name => "Conversation"
  has_many :conversations , :foreign_key => :rec_id , :class_name => "Conversation"

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@jobs = Job.all
  end
  def new
  	@job = Job.new
  end

  def create
  	@job = Job.new(job_params)
  	if @job.save
  		redirect_to jobs_path
  	else
  		root_path
  	end
  end

  def show
  	@job = Job.find(params[:id])
  end

  private
  def job_params
  	params.require(:job).permit(:company_name,
   :job_title,
   :job_location,
   :salary,
   :experience,
   :sector,
   :skill,
   :level_of_experience,
   :corporate_type,
   :job_description)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	before_action :authenticate_user!
  def index
  	@news = News.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
def index
		@posts = Post.all
	end
	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

 		# @post.update_attributes(user_id: current_user.id)
  		if @post.save
  			redirect_to @post
  		else
  			render 'new'
  		end
	end

	def update
  		@post = Post.find(params[:id])
 
  			if @post.update(post_params)
  			redirect_to @post
  			else
    		render 'edit'
  			end
	end

	def destroy
		@post = Post.find(params[:id])
  		@post.destroy
 		redirect_to posts_path
	end

	private
  	def post_params
    params.require(:post).permit(:title, :content)
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(params_user)
		if @user.save
			redirect_to root_path
		end
	end
private
def params_user
	params.require(:user).permit(:email, :password, :phone_no, :verification_code, :unique_id, :company_name, :hr_name, :hiring_agency,
	:sector,
    :skills,
    :level_of_experience,
    :experience,
    :corporate_type,
    :education_level,
    :major,
    :minor,
    :institution_type,
    :cerificate,
    :salary,
    :location,
    :city,
    :reloaction_status,
    :role)
end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end

  def trend
  end

  def faq
  end

  def terms_of_serives
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/faq.html.erb
<h1>FAQ's</h1>

<p>What do you mean by an anonymous?
In our anonymous platform, we do not accept or require you to submit the details of your identity. We do not have any data to reveal your identity. This way your information remains anonymous while your skills based job profile still will be available. An email with phone password verification is used to make sure that its a legitimate account. We do not ask nor share with employers your name, current or previous employer name, educational institutions attended or age. Gender is optional for you to reveal if its pertinent to the industry or skillset you bring to the job.
</p>
<p>
Various academic research and corporate have voiced need for anonymity in hiring.
</p><p>
Economist Article:
</p><p>
http://www.economist.com/news/business/21677214-anonymising-job-applications-eliminate-discrimination-not-easy-no-names-no-bias
</p><p>
Stanford law school:
</p><p>
http://www.stanfordlawreview.org/print/article/how-congress-could-reduce-job-discrimination-promoting-anonymous-hiring
</p>

app/views/welcomes/index.html.erb
<h1>Welcomes#index</h1>


<% if current_user == nil %>
<!-- <a href="/users/sign_up?signup_as=professional" data-no-turbolink = 'true'>Professional</a>

<a href="/users/sign_up?signup_as=employer" data-no-turbolink = 'true'>Employer</a>
 -->
<% elsif current_user.unique_id == nil %>

<%= link_to "Post a job", new_job_path %> 
<a href="/welcomes/?welcome_as=search" >Search for professionals</a>

<% else %>

<%= link_to "My messages" %> | <%= link_to "Search for job", jobs_path %>

<% end %>

</br>
</br>
</br>
</br>

<div align = "center">
<% if params[:welcome_as] == 'search'%>
	<% User.where(unique_id: nil).each do |user| %>
	<%= link_to user.email, user_path(user) %>--<%= user.unique_id%></br>

	<% end %>
<%= link_to 'back', welcomes_path%>
<% end %>
</div>

app/views/welcomes/privacy_policy.html.erb
<h1>Privacy Policy</h1>

<p>What do you mean by an anonymous?
In our anonymous platform, we do not accept or require you to submit the details of your identity. We do not have any data to reveal your identity. This way your information remains anonymous while your skills based job profile still will be available. An email with phone password verification is used to make sure that its a legitimate account. We do not ask nor share with employers your name, current or previous employer name, educational institutions attended or age. Gender is optional for you to reveal if its pertinent to the industry or skillset you bring to the job.
</p>
<p>
Various academic research and corporate have voiced need for anonymity in hiring.
</p><p>
Economist Article:
</p><p>
http://www.economist.com/news/business/21677214-anonymising-job-applications-eliminate-discrimination-not-easy-no-names-no-bias
</p><p>
Stanford law school:
</p><p>
http://www.stanfordlawreview.org/print/article/how-congress-could-reduce-job-discrimination-promoting-anonymous-hiring
</p>

app/views/welcomes/terms_of_serives.html.erb
<h1>Terms Of Services</h1>

<p>What do you mean by an anonymous?
In our anonymous platform, we do not accept or require you to submit the details of your identity. We do not have any data to reveal your identity. This way your information remains anonymous while your skills based job profile still will be available. An email with phone password verification is used to make sure that its a legitimate account. We do not ask nor share with employers your name, current or previous employer name, educational institutions attended or age. Gender is optional for you to reveal if its pertinent to the industry or skillset you bring to the job.
</p>
<p>
Various academic research and corporate have voiced need for anonymity in hiring.
</p><p>
Economist Article:
</p><p>
http://www.economist.com/news/business/21677214-anonymising-job-applications-eliminate-discrimination-not-easy-no-names-no-bias
</p><p>
Stanford law school:
</p><p>
http://www.stanfordlawreview.org/print/article/how-congress-could-reduce-job-discrimination-promoting-anonymous-hiring
</p>